### ISSUE TITLE
The section type "dreamform-license" is not valid

### ISSUE THREAD

**Issue by outline4** [mzur/kirby-form#19]
Hi, 

I've just purchased and installed kirby-dreamform for the first time. 

The plugin is created. 
The forms folder and the forms.txt as well. 

this is what I defined in the config.php

        use tobimori\DreamForm\Support\Menu;
	'panel.menu' => fn () => [
		'site' => Menu::site(),
		'forms' => Menu::forms(),
		'users',
		'system',
	],

	'tobimori.dreamform' => [
		// encryption secret for htmx attributes
		'secret' => '...',
		'layouts' => ['1/1', '1/2, 1/2', '1/3, 1/3, 1/3'],
		'mode' => 'htmx',
	],

When I visit the forms sidebar there's this message: 

`The section type "dreamform-license" is not valid`

Where do I enter the license number? 
I am on a live domain. 

Also: I don't see an icon like in the docs...

Another (unrelated) problem is that when I click, within the form builder, on new layout, the first layout is kinda bizzarre: 

<img width="496" alt="Bildschirmfoto 2024-11-19 um 14 50 41" src="https://github.com/user-attachments/assets/56b1cf8d-e409-423b-b94b-2638cd471287">

What am I doing wrong?

Be patient, it's my very first time I install this plugin. 

Cheers  
Stefan

**Comment by outline4** [comment]
btw: I've installed the plugin via composer.  
I am on kirby 4.4  
with php 8.3

**Comment by mzur** [comment]
This is the kirby-form plugin. For Dreamform go to https://github.com/tobimori/kirby-dreamform 😉

**Comment by outline4** [comment]
Oh man, I am so sorry! 

will post this over there!
